
    -- Enable Vector Extension for future AI features
    create extension if not exists vector;

    -- Products Table
    create table if not exists products (
        id bigint generated by default as identity primary key,
        name text not null,
        price double precision not null,
        currency text default 'EUR',
        unit text,
        store text not null,
        original_url text,
        image_url text,
        calories_100g integer,
        nutriscore text,
        last_enriched timestamp with time zone default timezone('utc'::text, now()),
        created_at timestamp with time zone default timezone('utc'::text, now())
    );

    -- Recipes Table
    create table if not exists recipes (
        id text primary key, -- TheMealDB IDs are strings
        title text not null,
        image_url text,
        instructions text,
        prep_time integer,
        serving_size integer,
        created_at timestamp with time zone default timezone('utc'::text, now())
    );

    -- Recipe Ingredients Link
    create table if not exists recipe_ingredients (
        id bigint generated by default as identity primary key,
        recipe_id text references recipes(id) on delete cascade,
        ingredient_name text not null,
        quantity text
    );

    -- Indexing for performance
    create index if not exists idx_products_name on products using gin(to_tsvector('english', name));
    create index if not exists idx_products_store on products(store);
    